services:
  infinity-search:
    image: duefix/infinity-search:1.0.0
    container_name: infinity-search
    restart: unless-stopped

    ports:
      - "18080:8080"

    volumes:
      - infinity-search-data:/data

volumes:
  infinity-search-data:
